### ISSUE TITLE
webrtc.lib 

### ISSUE THREAD

**Issue by MrsZ** [xjsXjtu/webrtc-native-demo-win#2]
您好。您的那个webrtc.lib 库是如何编译出来的呢？可以指导一下吗？谢谢啦。

**Comment by xjsXjtu** [comment]
基本就是按照官网：https://webrtc.org/native-code/development/，用gn生成工程，然后用ninja编译。
你先研究一下吧，如果可以翻墙，还是很容的。

这个不算是issue，我直接close了哈。

**Comment by MrsZ** [comment]
我编译的那个项目 lib库 得有 几百个 哈哈，您的这个就编译成一个啦？ 我的qq  863973433  可以讨论一下，目前正基于webrtc服务器 做pc端的 native  已经实现移动端和web的了 。谢谢啦
